"""cascade_deletion

Revision ID: 5e1298b968de
Revises: 6cc875b60be8
Create Date: 2022-05-02 18:08:27.708832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1298b968de'
down_revision = '6cc875b60be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
